describe('template spec', () => {
  it('passes', () => {
    //cy.visit('http://localhost:8000/')
    cy.visit('https://uat-ehaj.oss.net.bd')
    // cy.wait(5000)
    cy.get('header>nav>div>div>ul>li>a').contains('লগইন').click()
    // cy.wait(5000)
    cy.get('div#kc-social-providers ul>a').contains('হজযাত্রী/ গাইড লগইন').click();
    // cy.get(5000)
    cy.get('div#login_form_body div.login-panel-body div>input[type=text][name=mobile_no]').type('01609149406')
    // cy.wait(5000)
    cy.get('div#login_form_body div.login-panel-body div>input[type=password][name=password]').type('640087@m')
    // cy.wait(5000)
    cy.get('div#login_form_body div.login-panel-body div>button#next_btn').contains('Sign in').click();
    // cy.wait(5000)
    cy.url().should('include', '/my-desk')
    // cy.wait(5000)
    //cy.visit('https://uat-ehaj.oss.net.bd/guides/index#/guide-application-list')
    cy.get('div.hajj-dashboard-container>aside>div>div>a>span.dm-text').contains('হজ গাইড').click()
    // cy.wait(5000)
    cy.get('div#newApplicationBtn>div>span.list-btn-text').contains('নতুন আবেদন').click()
    //cy.wait(5000)
    cy.get('input[type=radio][name=prev_hajj_experience][value="yes"]').click({force: true})
    //cy.wait(5000)
    cy.get('input[type=text][placeholder="সর্বশেষ ট্রাকিং নম্বর লিখুন"]').type('H175DD3B2B')
    //cy.wait(5000)
    cy.get('div.bd-card-footer>div>button>span').contains('Next').click()
    cy.wait(5000)
    cy.get('div>input.dp__input_reg[placeholder="Select Date"]').click()
    cy.wait(5000)
    cy.get('div.dp__month_year_select[aria-label="Open years overlay"]').click()
    cy.wait(5000)
    cy.get('div.dp__overlay').contains('1998').click()
    cy.wait(5000)
    cy.get('div.dp__cell_inner').contains('15').click()
    cy.wait(5000)
    cy.get('div>input[type="number"][placeholder="জাতীয় পরিচয় নম্বর"]').type(4329870922)
    cy.wait(5000)
    cy.get('div#birthPlace>div>span>span>span>span#select2--container').click()
    cy.get(5000)
    cy.get('span>input.select2-search__field').type('দিনাজপুর{enter}')
    cy.wait(5000)
    cy.get('select.hajj-select2[data-v-0dc85e4d]').select('female')
    cy.wait(5000)
    cy.get('div.upload-user-photo>div>div>div>input[type="file"]#uploadBtn').selectFile('C:/Users/karima jaman/Downloads/cyprus test automation.png', { action:  'drag-drop'})
    cy.wait(5000)
    cy.get('div.user-guide-address[data-v-8da79fd6]>div>input[type="text"][placeholder="পোষ্ট কোড"]').type('2345')
    cy.wait(5000)
    cy.get('div>select.hajj-select2[data-v-8da79fd6]').select('7')
    cy.wait(5000)
    cy.get('div#permanentDistrict>div>span>span>span>span#select2--container').click()
    cy.wait(5000)
    cy.get('span>input[type="search"].select2-search__field').type('ফরিদপুর{enter}')
    cy.wait(5000)
    cy.get('div#permanentThana>div>span>span>span>span#select2--container').click()
    cy.wait(5000)
    cy.get('span>input[type="search"].select2-search__field').type('ভাংগা{enter}')
    cy.wait(5000)
    cy.get('div.user-guide-address[data-v-8da79fd6]>div>input[type="text"][placeholder="ঠিকানা"]').type('Sonakhola')
    cy.wait(5000)
    cy.get('div>input[type="checkbox"]#same_address').click()
    cy.wait(7000)
    cy.get('div>input[type="radio"][name="hajj_guide_job_holder"][value="No"]').click({force: true})
    cy.wait(4000)
    cy.get('div>input[type="checkbox"]#user_reg_terms').click()
    cy.wait(5000)
    cy.get('div>button[type="submit"]>span').contains('Save as Draft').click()

  })
})